Draft: Cmake
nest/nest-gpu pull request #45
Opened 2022-10-27 14:13 UTC by JoseJVS

First working CMake implementation, with all tests succeeding.
Still in draft as testing and documentation targets are not yet implemented (code commented out to serve as roadmap), however I think they would be more appropriate for another pull request.
Furthermore, the configuration summary still needs to be re-implemented (but not a necessary feature).

2022-10-31 11:02 UTC, jhnnsnk commented
Thank you very much, @JoseJVS!
At least the documentation of how to install NEST GPU now should be updated as part of this PR, I think. Maybe @gmtiddia could help with that?
Apart from that I agree that some features could become follow-up PRs. Maybe we could directly create new issues and move the respective files (the ones copied from plain NEST) from this PR to another draft PR?

2022-10-31 11:07 UTC, gmtiddia commented
Sure, I'll help with the documentation update for this PR.

2022-11-21 11:15 UTC, JoseJVS commented
With the configure summary module adapted to NEST GPU, the CMake implementation is now fully functional.
There are still the documentation and testing targets that are not yet ready to be implemented but those can be worked on other PRs.

2022-12-01 16:21 UTC, terhorstd commented on CMakeLists.txt
> +option( cythonize-pynest "Use Cython to cythonize pynestkernel.pyx [default=ON]. If OFF, PyNEST has to be build from a pre-cythonized pynestkernel.pyx." ON )
This might come in future, when there actually is a Cython part. for now this would be unused and might be confusing.
```suggestion
```

2022-12-01 16:55 UTC, terhorstd requested changes
Seems to be OK, some questions and a few minor changes to look at again.
Thanks for the work!

2022-12-01 16:55 UTC, terhorstd commented on cmake/CheckIncludesSymbols.cmake
> +    " is up-to-date (3.18+)."
Minimum required version is specified as 3.17 in `/CMakeLists.txt`, either change that to `3.18`, or rephrase to `(3.17+)` here.

2022-12-01 16:55 UTC, terhorstd commented on cmake/CheckIncludesSymbols.cmake
> +# PyNEST can only act as an entry point; it does not need to be included in the other objects' RPATH itself.
Does this also hold for NEST GPU?
```
# PyNEST can only act as an entry point; it does not need to be included in the other objects' RPATH itself.
```

2022-12-01 16:55 UTC, terhorstd commented on cmake/ConfigureSummary.cmake
> +  message( "or go to https://www.nest-simulator.org/community to find out how to" )
These links should probably go to appropriate NEST GPU readthedocs pages.

2022-12-01 16:55 UTC, terhorstd commented on doc/installation/index.rst
> +``<nestgpu_source_dir>/python/test``, where the ``src/path`` is the install path given
```suggestion
``<nestgpu_source_dir>/python/test``, where the ``<nestgpu_source_dir>`` is the install path given
```

2022-12-01 17:19 UTC, gtrensch requested changes
Many thanks for this work :+1:. 
There is a minor issue with CMake option -Dwith-optimize that has already been addressed in NEST. See issue #51. Please see also the comments.

2022-12-06 14:35 UTC, JoseJVS commented
Updated branch with suggested changes from reviewers

2022-12-14 11:32 UTC, terhorstd approved these changes
This looks solid to me now!
Thanks for all the work!!!
:+1:

2022-12-15 19:43 UTC, gtrensch approved these changes
Looks good to me. 👍

2023-01-09 10:21 UTC, gmtiddia approved these changes

2023-01-09 10:23 UTC, merged